### PR TITLE
Air Quality Monitor Python Script

### PR DESCRIPTION
**Pull request by Rutuj-Runwal**
Added a separate folder along with the code, output images and readme file

In referene to issue no #4

### CODE REVIEW

**Comment by Rutuj-Runwal** [comment]
@KrishGaur1354 Take a look

**Comment by KrishGaur1354** [comment]
Thanks for your Submitting your Project. Don't forget to follow Us.

**Comment by Rutuj-Runwal** [comment]
> Thanks for your Submitting your Project. Don't forget to follow Us.

Yes surely

Bro one more thing, sorry for the trouble.
The correct label is "hacktoberfest-accepted" can you correct it please.

Also can we design a guideline for issue and pull request submission as we can see many requests are not up to the mark and some are missing many things so if you allow me to create a template for issues it will be great!

**Comment by KrishGaur1354** [comment]
@Rutuj-Runwal Yeah Sure

**Pull request merged**
