### PR TITLE
quiz project

### PR DESCRIPTION
**Pull request by codemaniac-sahil**
Hello @KrishGaur1354 I created this quiz projects. Would you please check the project.

### CODE REVIEW

**Comment by KrishGaur1354** [comment]
Kindly create a Folder with the Project name and add the coded file to the folder. Also, add output pictures for the code.

**Comment by codemaniac-sahil** [comment]
I already created folder and also added the code file.

**Comment by codemaniac-sahil** [comment]
> Kindly create a Folder with the Project name and add the coded file to the folder. Also, add output pictures for the code.

@KrishGaur1354 Everything is done. Would you please check.

**Comment by KrishGaur1354** [comment]
Thanks for your Submitting your Project. Don't forget to follow Us.

**Pull request merged**
